// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCxHNdSlLZtzR8ADHjCHQeAy6KIk3vqwY',
    appId: '1:587934422956:web:af09f1d471b01c9df2cc09',
    messagingSenderId: '587934422956',
    projectId: 'emailpasswordauth-97281',
    authDomain: 'emailpasswordauth-97281.firebaseapp.com',
    storageBucket: 'emailpasswordauth-97281.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtDuIKcDWnxxS96Sv9gRSkAyd2swgs8yY',
    appId: '1:587934422956:android:30eaf4ea8a37fb07f2cc09',
    messagingSenderId: '587934422956',
    projectId: 'emailpasswordauth-97281',
    storageBucket: 'emailpasswordauth-97281.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB18E8TmgWk-su2C0vaID_I2-FkTh1kLSY',
    appId: '1:587934422956:ios:69343caa246c084ef2cc09',
    messagingSenderId: '587934422956',
    projectId: 'emailpasswordauth-97281',
    storageBucket: 'emailpasswordauth-97281.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB18E8TmgWk-su2C0vaID_I2-FkTh1kLSY',
    appId: '1:587934422956:ios:6457fb68150eb212f2cc09',
    messagingSenderId: '587934422956',
    projectId: 'emailpasswordauth-97281',
    storageBucket: 'emailpasswordauth-97281.appspot.com',
    iosBundleId: 'com.example.task.RunnerTests',
  );
}
